
// ================= PRODUCTS =================

export const products = [
  {
    id: 101,
    categoryId: 1,
    title: "Modern Grey Sofa",
    slug: "modern-grey-sofa",
    brand: "Crafture",
    sku: "CR-SOF-001",
    price: 25999,
    mrp: 31999,
    thumbnail:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1200&auto=format&fit=crop",
    material: "Premium Fabric",
    color: "Grey",
    seatingCapacity: 3,
    dimensions: {
      height: "34 inch",
      width: "84 inch",
      length: "36 inch",
      weight: "42 kg",
    },
    warranty: "2 Years",
    assemblyRequired: true,
    rating: 4.5,
    totalReviews: 245,
    featured: true,
    bestseller: true,
    trending: true,
    description:
      "Premium modern grey sofa designed for luxury living rooms.",
    features: [
      "High density foam",
      "Premium fabric finish",
      "Strong wooden frame",
      "Comfort seating",
    ],
    careInstructions: [
      "Avoid direct sunlight",
      "Clean with dry cloth",
      "Keep away from water",
    ],
    tags: ["modern", "living room", "luxury"],
    createdAt: "2026-05-01",
  },

  {
    id: 102,
    categoryId: 2,
    title: "King Size Wooden Bed",
    slug: "king-size-wooden-bed",
    brand: "Crafture",
    sku: "CR-BED-001",
    price: 38999,
    mrp: 45999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop",
    material: "Solid Wood",
    color: "Walnut Brown",
    dimensions: {
      height: "48 inch",
      width: "78 inch",
      length: "84 inch",
      weight: "68 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.8,
    totalReviews: 180,
    featured: true,
    bestseller: false,
    trending: true,
    description:
      "Elegant king size wooden bed with premium finish.",
    features: [
      "Termite resistant wood",
      "Premium polish finish",
      "Strong frame support",
    ],
    careInstructions: [
      "Use dry cotton cloth",
      "Avoid water exposure",
    ],
    tags: ["bedroom", "wooden", "luxury"],
    createdAt: "2026-05-01",
  },

  {
    id: 103,
    categoryId: 1,
    title: "Luxury Blue Velvet Sofa",
    slug: "luxury-blue-velvet-sofa",
    brand: "Crafture",
    sku: "CR-SOF-002",
    price: 28999,
    mrp: 34999,
    thumbnail:
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1200&auto=format&fit=crop",
    material: "Velvet Fabric",
    color: "Royal Blue",
    seatingCapacity: 3,
    dimensions: {
      height: "35 inch",
      width: "86 inch",
      length: "38 inch",
      weight: "45 kg",
    },
    warranty: "3 Years",
    assemblyRequired: true,
    rating: 4.6,
    totalReviews: 164,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Elegant velvet sofa for premium living interiors.",
    features: [
      "Velvet upholstery",
      "Soft cushions",
      "Wooden legs",
      "Premium comfort",
    ],
    careInstructions: [
      "Vacuum regularly",
      "Avoid moisture",
    ],
    tags: ["sofa", "velvet", "modern"],
    createdAt: "2026-05-02",
  },

  {
    id: 104,
    categoryId: 1,
    title: "Compact Beige Sofa",
    slug: "compact-beige-sofa",
    brand: "Crafture",
    sku: "CR-SOF-003",
    price: 19999,
    mrp: 24999,
    thumbnail:
      "https://images.unsplash.com/photo-1484101403633-562f891dc89a?q=80&w=1200&auto=format&fit=crop",
    material: "Fabric",
    color: "Beige",
    seatingCapacity: 2,
    dimensions: {
      height: "32 inch",
      width: "70 inch",
      length: "34 inch",
      weight: "35 kg",
    },
    warranty: "2 Years",
    assemblyRequired: false,
    rating: 4.2,
    totalReviews: 90,
    featured: false,
    bestseller: true,
    trending: false,
    description: "Compact sofa ideal for apartments and studios.",
    features: [
      "Compact design",
      "Soft foam",
      "Easy maintenance",
    ],
    careInstructions: [
      "Use dry cloth",
      "Keep away from heat",
    ],
    tags: ["compact", "small-space", "beige"],
    createdAt: "2026-05-03",
  },

  {
    id: 105,
    categoryId: 1,
    title: "Brown Leather Recliner Sofa",
    slug: "brown-leather-recliner-sofa",
    brand: "Crafture",
    sku: "CR-SOF-004",
    price: 45999,
    mrp: 55999,
    thumbnail:
      "https://images.unsplash.com/photo-1512212621149-107ffe572d2f?q=80&w=1200&auto=format&fit=crop",
    material: "Leather",
    color: "Brown",
    seatingCapacity: 4,
    dimensions: {
      height: "40 inch",
      width: "92 inch",
      length: "40 inch",
      weight: "72 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.9,
    totalReviews: 310,
    featured: true,
    bestseller: true,
    trending: true,
    description: "Luxury recliner sofa with premium leather finish.",
    features: [
      "Recliner seats",
      "Premium leather",
      "Extra cushioning",
    ],
    careInstructions: [
      "Use leather cleaner",
      "Avoid sharp objects",
    ],
    tags: ["recliner", "leather", "luxury"],
    createdAt: "2026-05-04",
  },

  {
    id: 106,
    categoryId: 2,
    title: "Queen Size Storage Bed",
    slug: "queen-size-storage-bed",
    brand: "Crafture",
    sku: "CR-BED-002",
    price: 42999,
    mrp: 49999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693536294-233b40443c4c?q=80&w=1200&auto=format&fit=crop",
    material: "Engineered Wood",
    color: "Teak",
    dimensions: {
      height: "46 inch",
      width: "72 inch",
      length: "82 inch",
      weight: "74 kg",
    },
    warranty: "4 Years",
    assemblyRequired: true,
    rating: 4.7,
    totalReviews: 205,
    featured: true,
    bestseller: true,
    trending: false,
    description: "Spacious queen size bed with hydraulic storage.",
    features: [
      "Hydraulic storage",
      "Scratch resistant",
      "Modern design",
    ],
    careInstructions: [
      "Avoid water",
      "Use soft cloth",
    ],
    tags: ["bed", "storage", "queen-size"],
    createdAt: "2026-05-05",
  },

  {
    id: 107,
    categoryId: 2,
    title: "Minimal Platform Bed",
    slug: "minimal-platform-bed",
    brand: "Crafture",
    sku: "CR-BED-003",
    price: 31999,
    mrp: 38999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop",
    material: "Solid Wood",
    color: "Natural Oak",
    dimensions: {
      height: "40 inch",
      width: "76 inch",
      length: "80 inch",
      weight: "58 kg",
    },
    warranty: "3 Years",
    assemblyRequired: true,
    rating: 4.4,
    totalReviews: 120,
    featured: false,
    bestseller: false,
    trending: true,
    description: "Minimal wooden platform bed for modern bedrooms.",
    features: [
      "Low height design",
      "Strong support",
      "Natural finish",
    ],
    careInstructions: [
      "Dust weekly",
      "Avoid direct sunlight",
    ],
    tags: ["minimal", "wooden", "bedroom"],
    createdAt: "2026-05-06",
  },

  {
    id: 108,
    categoryId: 3,
    title: "6 Seater Marble Dining Table",
    slug: "6-seater-marble-dining-table",
    brand: "Crafture",
    sku: "CR-DIN-001",
    price: 55999,
    mrp: 65999,
    thumbnail:
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?q=80&w=1200&auto=format&fit=crop",
    material: "Marble Top",
    color: "White",
    dimensions: {
      height: "30 inch",
      width: "72 inch",
      length: "40 inch",
      weight: "85 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.8,
    totalReviews: 156,
    featured: true,
    bestseller: true,
    trending: true,
    description: "Premium marble dining table for luxury interiors.",
    features: [
      "Marble finish",
      "Strong steel legs",
      "6 seater capacity",
    ],
    careInstructions: [
      "Clean spills immediately",
      "Use placemats",
    ],
    tags: ["dining", "marble", "luxury"],
    createdAt: "2026-05-07",
  },

  {
    id: 109,
    categoryId: 3,
    title: "Wooden Family Dining Set",
    slug: "wooden-family-dining-set",
    brand: "Crafture",
    sku: "CR-DIN-002",
    price: 47999,
    mrp: 55999,
    thumbnail:
      "https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=1200&auto=format&fit=crop",
    material: "Solid Wood",
    color: "Walnut",
    dimensions: {
      height: "30 inch",
      width: "68 inch",
      length: "38 inch",
      weight: "76 kg",
    },
    warranty: "4 Years",
    assemblyRequired: true,
    rating: 4.5,
    totalReviews: 140,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Classic wooden dining set with elegant finish.",
    features: [
      "Premium wood",
      "Smooth polish",
      "Family seating",
    ],
    careInstructions: [
      "Avoid scratches",
      "Use dry cloth",
    ],
    tags: ["dining", "wooden", "family"],
    createdAt: "2026-05-08",
  },

  {
    id: 110,
    categoryId: 4,
    title: "Modern Office Chair",
    slug: "modern-office-chair",
    brand: "Crafture",
    sku: "CR-CHR-001",
    price: 12999,
    mrp: 16999,
    thumbnail:
      "https://images.unsplash.com/photo-1505843490701-5be5d1b9c2a6?q=80&w=1200&auto=format&fit=crop",
    material: "Mesh Fabric",
    color: "Black",
    dimensions: {
      height: "48 inch",
      width: "24 inch",
      length: "24 inch",
      weight: "18 kg",
    },
    warranty: "2 Years",
    assemblyRequired: true,
    rating: 4.4,
    totalReviews: 250,
    featured: true,
    bestseller: true,
    trending: false,
    description: "Ergonomic office chair with lumbar support.",
    features: [
      "Adjustable height",
      "Breathable mesh",
      "360 swivel",
    ],
    careInstructions: [
      "Clean with dry cloth",
      "Avoid excess weight",
    ],
    tags: ["office", "ergonomic", "chair"],
    createdAt: "2026-05-09",
  },

  {
    id: 111,
    categoryId: 1,
    title: "Minimal White Linen Sofa",
    slug: "minimal-white-linen-sofa",
    brand: "Crafture",
    sku: "CR-SOF-005",
    price: 27999,
    mrp: 33999,
    thumbnail:
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1200&auto=format&fit=crop",
    material: "Linen Fabric",
    color: "White",
    seatingCapacity: 3,
    dimensions: {
      height: "34 inch",
      width: "82 inch",
      length: "36 inch",
      weight: "40 kg",
    },
    warranty: "3 Years",
    assemblyRequired: true,
    rating: 4.6,
    totalReviews: 190,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Elegant linen sofa for modern interiors.",
    features: [
      "Soft linen fabric",
      "Premium comfort",
      "Solid wooden frame",
    ],
    careInstructions: [
      "Vacuum regularly",
      "Avoid liquid spills",
    ],
    tags: ["sofa", "linen", "modern"],
    createdAt: "2026-05-10",
  },

  {
    id: 112,
    categoryId: 1,
    title: "Olive Green Sectional Sofa",
    slug: "olive-green-sectional-sofa",
    brand: "Crafture",
    sku: "CR-SOF-006",
    price: 52999,
    mrp: 62999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop",
    material: "Premium Fabric",
    color: "Olive Green",
    seatingCapacity: 5,
    dimensions: {
      height: "36 inch",
      width: "110 inch",
      length: "70 inch",
      weight: "88 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.8,
    totalReviews: 275,
    featured: true,
    bestseller: true,
    trending: true,
    description: "Large sectional sofa designed for spacious living rooms.",
    features: [
      "L-shape design",
      "Deep seating",
      "Premium fabric finish",
    ],
    careInstructions: [
      "Use dry cloth",
      "Avoid direct sunlight",
    ],
    tags: ["sectional", "green", "luxury"],
    createdAt: "2026-05-11",
  },

  {
    id: 113,
    categoryId: 2,
    title: "Modern Upholstered Bed",
    slug: "modern-upholstered-bed",
    brand: "Crafture",
    sku: "CR-BED-004",
    price: 48999,
    mrp: 57999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693536294-233b40443c4c?q=80&w=1200&auto=format&fit=crop",
    material: "Velvet Fabric",
    color: "Light Grey",
    dimensions: {
      height: "52 inch",
      width: "78 inch",
      length: "84 inch",
      weight: "72 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.7,
    totalReviews: 198,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Luxury upholstered bed with premium headboard.",
    features: [
      "Soft fabric finish",
      "Strong wooden support",
      "Modern design",
    ],
    careInstructions: [
      "Use dry cloth",
      "Avoid moisture",
    ],
    tags: ["bed", "upholstered", "luxury"],
    createdAt: "2026-05-12",
  },

  {
    id: 114,
    categoryId: 2,
    title: "Rustic Wooden Cot",
    slug: "rustic-wooden-cot",
    brand: "Crafture",
    sku: "CR-BED-005",
    price: 29999,
    mrp: 36999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop",
    material: "Solid Teak Wood",
    color: "Dark Walnut",
    dimensions: {
      height: "44 inch",
      width: "74 inch",
      length: "80 inch",
      weight: "64 kg",
    },
    warranty: "4 Years",
    assemblyRequired: true,
    rating: 4.5,
    totalReviews: 142,
    featured: false,
    bestseller: true,
    trending: false,
    description: "Traditional wooden cot with rustic finish.",
    features: [
      "Solid teak wood",
      "Durable build",
      "Classic design",
    ],
    careInstructions: [
      "Dust regularly",
      "Avoid water",
    ],
    tags: ["cot", "wooden", "rustic"],
    createdAt: "2026-05-13",
  },

  {
    id: 115,
    categoryId: 3,
    title: "Round Glass Dining Table",
    slug: "round-glass-dining-table",
    brand: "Crafture",
    sku: "CR-DIN-003",
    price: 35999,
    mrp: 42999,
    thumbnail:
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?q=80&w=1200&auto=format&fit=crop",
    material: "Glass Top",
    color: "Transparent",
    dimensions: {
      height: "30 inch",
      width: "54 inch",
      length: "54 inch",
      weight: "48 kg",
    },
    warranty: "3 Years",
    assemblyRequired: true,
    rating: 4.4,
    totalReviews: 110,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Modern round dining table with tempered glass top.",
    features: [
      "Tempered glass",
      "Steel frame",
      "Compact design",
    ],
    careInstructions: [
      "Clean with glass cleaner",
      "Avoid sharp objects",
    ],
    tags: ["glass", "dining", "modern"],
    createdAt: "2026-05-14",
  },

  {
    id: 116,
    categoryId: 3,
    title: "8 Seater Wooden Dining Table",
    slug: "8-seater-wooden-dining-table",
    brand: "Crafture",
    sku: "CR-DIN-004",
    price: 68999,
    mrp: 78999,
    thumbnail:
      "https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=1200&auto=format&fit=crop",
    material: "Solid Wood",
    color: "Mahogany",
    dimensions: {
      height: "30 inch",
      width: "92 inch",
      length: "42 inch",
      weight: "98 kg",
    },
    warranty: "6 Years",
    assemblyRequired: true,
    rating: 4.9,
    totalReviews: 240,
    featured: true,
    bestseller: true,
    trending: true,
    description: "Large wooden dining table for family gatherings.",
    features: [
      "8 seater",
      "Premium wood finish",
      "Strong support",
    ],
    careInstructions: [
      "Use coasters",
      "Avoid heat exposure",
    ],
    tags: ["dining", "wooden", "family"],
    createdAt: "2026-05-15",
  },

  {
    id: 118,
    categoryId: 4,
    title: "Minimal Wooden Chair",
    slug: "minimal-wooden-chair",
    brand: "Crafture",
    sku: "CR-CHR-003",
    price: 8999,
    mrp: 11999,
    thumbnail:
      "https://images.unsplash.com/photo-1519947486511-46149fa0a254?q=80&w=1200&auto=format&fit=crop",
    material: "Oak Wood",
    color: "Natural Oak",
    dimensions: {
      height: "36 inch",
      width: "18 inch",
      length: "18 inch",
      weight: "9 kg",
    },
    warranty: "2 Years",
    assemblyRequired: false,
    rating: 4.3,
    totalReviews: 88,
    featured: false,
    bestseller: true,
    trending: false,
    description: "Minimal wooden chair with Scandinavian styling.",
    features: [
      "Solid oak wood",
      "Compact design",
      "Lightweight",
    ],
    careInstructions: [
      "Use dry cloth",
      "Avoid moisture",
    ],
    tags: ["chair", "wooden", "minimal"],
    createdAt: "2026-05-17",
  },

  {
    id: 119,
    categoryId: 5,
    title: "Sliding Door Wardrobe",
    slug: "sliding-door-wardrobe",
    brand: "Crafture",
    sku: "CR-WRD-001",
    price: 64999,
    mrp: 74999,
    thumbnail:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1200&auto=format&fit=crop",
    material: "Engineered Wood",
    color: "Walnut",
    dimensions: {
      height: "84 inch",
      width: "72 inch",
      length: "24 inch",
      weight: "110 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.7,
    totalReviews: 170,
    featured: true,
    bestseller: true,
    trending: true,
    description: "Spacious wardrobe with smooth sliding doors.",
    features: [
      "Sliding mechanism",
      "Large storage",
      "Premium finish",
    ],
    careInstructions: [
      "Avoid water",
      "Clean with soft cloth",
    ],
    tags: ["wardrobe", "storage", "modern"],
    createdAt: "2026-05-18",
  },

  {
    id: 120,
    categoryId: 5,
    title: "Mirror Finish Wardrobe",
    slug: "mirror-finish-wardrobe",
    brand: "Crafture",
    sku: "CR-WRD-002",
    price: 72999,
    mrp: 82999,
    thumbnail:
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200&auto=format&fit=crop",
    material: "MDF Wood",
    color: "White",
    dimensions: {
      height: "86 inch",
      width: "78 inch",
      length: "26 inch",
      weight: "124 kg",
    },
    warranty: "5 Years",
    assemblyRequired: true,
    rating: 4.8,
    totalReviews: 201,
    featured: true,
    bestseller: false,
    trending: true,
    description: "Elegant wardrobe with full mirror finish.",
    features: [
      "Mirror doors",
      "Premium shelves",
      "Soft close hinges",
    ],
    careInstructions: [
      "Clean mirrors regularly",
      "Avoid harsh chemicals",
    ],
    tags: ["wardrobe", "mirror", "luxury"],
    createdAt: "2026-05-19",
  },
];
